### ISSUE TITLE
Firefox version is missing

### ISSUE THREAD

**Issue by remixer-dec** [xuejianxianzun/PixivBatchDownloader#11]
The link that you provided in README is no longer accessible.
P.S. It would be nice if you also uploaded extension file in github's "releases" tab.

**Comment by xuejianxianzun** [comment]
Because Firefox has removed my extension twice, I won't try it anymore.
If you want to use local extensions, Chrome is also a better choice, because Firefox needs to sign the extension package for long-lasting use. Chrome can load local extensions directly and keep them.
I will update the README later to remove the Firefox entries.
Thanks you!
