### ISSUE TITLE
Downloads have stopped

### ISSUE THREAD

**Issue by slelmir** [xuejianxianzun/PixivBatchDownloader#126]
I started download a couple pages of artwork, but now the program won't download anymore and the download bars are stuck on complete on the same files that it says it's downloading. I switched my wifi source which didn't work, and downloaded an image from google images which did work, and I have enough space on my hard drive.

**Comment by slelmir** [comment]
This is after I crawled some pages of works, restarted my computer, and tried to start the downloads, my chrome browser kept crashing every time I opened it up and had to uninstall and reinstall the whole browser deleting my browser history. So this is after I've redownloaded the program, it should be clean

**Comment by slelmir** [comment]
Ok, the downloads resumed again after I refreshed the page, so I guess I just wonder why they stopped in the first place? When I opened another window when the downloads stopped I got a message that something was added to the downloader, so maybe it messed up because it was updated with a new feature?

**Comment by xuejianxianzun** [comment]
The main reason for the download error is network problems, but I am not sure if your network had problems at that time.
If the problem is not caused by the network, it is difficult to determine the cause of the problem.
When the download fails, you can try to refresh the page or switch networks.
It looks like you can download normally.
I'm going to bed, good night~
