### ISSUE TITLE
Is it possible to share as a userscript?

### ISSUE THREAD

**Issue by dpalacio** [xuejianxianzun/PixivBatchDownloader#139]
Can this extension be shared like a user script to be installed in Greasemonkey, Tampermonkey, Violentmonkey, etc. to be able to use it in Firefox?

**Comment by xuejianxianzun** [comment]
This is possible, but it is not easy to do.
This requires replacing some of the Chrome APIs with Tampermonkey's APIs, but I'm not sure if it can be completely consistent.
This downloader was userscript at the beginning, but because the experience is not as good as the Chrome extension, I stopped the maintenance of the userscript version.
The firefox extension also existed before, but because of a security restriction of firefox, it took up a lot of cpu and memory resources when downloading, so the firefox version is no longer maintained.
