### ISSUE TITLE
命名規則がうまく作動しません

### ISSUE THREAD

**Issue by cogaram** [xuejianxianzun/PixivBatchDownloader#161]
{series_order} {series_title}/{user} - {title} ({id_num}) {p_num}

この規則がイラストでエラーを起こします。

マンガなどのシリーズのもでは問題ありません。

{series_order} {series_title}

この部分が上手く動かないようです。

**Comment by xuejianxianzun** [comment]
Your naming rule `{series_order} {series_title}` has a space in between.
If the work you download does not belong to a certain series, then the results of `{series_order}` and `{series_title}` are both empty values (no characters are generated).
So there will be a space at the beginning of your file name, followed by a slash. This resulted in an error.
For now, you can remove this space so that the file can be downloaded. I will fix this anomaly in the next version.
ps: Because I do not speak Japanese, I translated the reply into English.

**Comment by cogaram** [comment]
sorry. Since the tool supports Japanese, I thought that you could read Japanese.
And thanks for putting it in the next patch.

I'm sorry with the translator

**Comment by xuejianxianzun** [comment]
Haha, actually my friend translated the Japanese text for me.
