### ISSUE TITLE
Persistent Configuration

### ISSUE THREAD

**Issue by CyberSolutions8799** [xuejianxianzun/PixivBatchDownloader#180]
I have a habit of clearing the browser's data everyday after use. Whenever I do so Powerful Pixiv Downloader looses it's configuration and I have to import the settings every time.

If possible please make the settings persistent like any other browser extensions.

**Comment by xuejianxianzun** [comment]
I will consider this.
This requires requesting a new permission: `storage`.
In addition, not all data can be stored persistently. Only configuration data will be stored persistently.
Because the storage limit of `chrome.storage.sync` is 100KB, the following data will not be stored in `chrome.storage`:
1. Download records
2. Data of unfinished tasks
3. Background image

**Comment by xuejianxianzun** [comment]
The 11.5.0 version saves the settings persistently.
Now you can install it offline, or wait for automatic updates later.
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v11.5.0

**Comment by CyberSolutions8799** [comment]
@xuejianxianzun Thanks!
