### ISSUE TITLE
[New Feature] Access extension's configuration without visiting Pixiv

### ISSUE THREAD

**Issue by CyberSolutions8799** [xuejianxianzun/PixivBatchDownloader#195]
**Example:** 
![Example](https://user-images.githubusercontent.com/57856900/156592399-5d9d3822-0f2f-4c54-8092-4d8852318d8c.JPG)

**Comment by xuejianxianzun** [comment]
1. The downloader must be on the pixiv page to use it. It cannot be used without access to pixiv, and it is not practical to modify the configuration at this time.
2. Now you can set different configuration in each pixiv page. This is a useful feature, because when opening multiple pixiv pages, you might temporarily turn on an option or filter and want it to only work on that page.
If using the way in the picture, all pages must use the same configuration. This will cause inconvenience.

**Comment by CyberSolutions8799** [comment]
> Now you can set different configuration in each pixiv page.

Oh! I didn't know about this feature. Thanks for letting me know.
But is it possible to just provide the Import & Export Settings option without visiting pixiv page?

**Comment by xuejianxianzun** [comment]
More detailed instructions:
When you change the settings in one page, it will not affect the settings of other pages.
So you can start crawling with different settings in different pages.
When the page is refreshed (or newly opened), it will use the latest settings.

> Import & Export Settings option without visiting pixiv page
No such plan now
