### ISSUE TITLE
Is there a way to update my downloads folders with new bookmarks

### ISSUE THREAD

**Issue by EthanBoiLol** [xuejianxianzun/PixivBatchDownloader#196]
Hi, I really like this extension...however I have one main issue

I have around 50k bookmarks, and yes, I did download all of them, but after a couple months it felt outdated, so I wanted to add new ones

the issue is that the download restarts so I have to wait for the downloader to install every single art instead of the new ones, and I didn't want to wait

Can you add a feature that will detect what I have already installed, I still have the original name saved (the one with the ID) so I was hoping you can program it to detect those IDS and just add on to it...sorry I'm not an export on javascript. Thanks :)

--
嗨，我真的很喜歡這個擴展...但是我有一個主要問題

我有大約 50,000 個書籤，是的，我確實下載了所有書籤，但幾個月後感覺已經過時了，所以我想添加新的

問題是下載重新開始，所以我必須等待下載器安裝每一個藝術而不是新的，我不想等待

您能否添加一項功能來檢測我已經安裝的內容，我仍然保存了原始名稱（帶有 ID 的名稱）所以我希望您可以對其進行編程以檢測這些 IDS 並添加到它...對不起我不是 javascript 的出口商。謝謝 ：）

**Comment by xuejianxianzun** [comment]
There is no good way now. You can try to find out how many pages were last downloaded and then download new pages.
For example, there were 1000 pages last time, and now there are 1200 pages, then you start crawling on page 1, set the number of pages to be crawled to 200, and you can only download the newly added bookmarks.
Another way is to enable the "Don't download duplicate files" setting so that the downloader will not download the already downloaded works repeatedly. But this feature is not always reliable, and clearing the browser data can cause the downloader's records to be lost.
---------
现在没有好的办法。你可以尝试找到上次下载到了多少页，然后下载新的页面。
例如上次抓取时有 1000 页，现在有 1200 页，那么你在第 1 页开始抓取，设置抓取页数为 200，就可以只下载新增的书签。
另一种办法是，启用“不下载重复文件”的设置，下载器就不会重复下载已经下载过的作品。但是这个功能并不总是可靠的，清除浏览器数据会导致下载器的记录丢失。
