### ISSUE TITLE
Error 429 

### ISSUE THREAD

**Issue by jack652** [xuejianxianzun/PixivBatchDownloader#287]
after around 10 seconds the extension says
```
Error code: 429 (Too many requests). The downloader will re-crawl it.
Pixiv returned empty data. The downloader has paused crawling and will resume crawling after a few minutes. (429)
```

**Comment by xuejianxianzun** [comment]
Error 429 encountered while crawling:
This is Pixiv's anti-crawler measure. That's what happens when you grab too many works in a short period of time.
Even with a 429 error, the downloader can still complete the crawl, it just takes more time than before. (The downloader will re-crawl works with 429 errors, so you don't have to worry about missing works.)
When a 429 error occurs, you cannot browse Pixiv works normally because your account is temporarily restricted, so changing your IP will not solve this problem.
If you don't want to encounter 429 errors, you can enable "Slow down crawl" in the downloader's settings.
