### ISSUE TITLE
duplicate download for user cover and user avatar

### ISSUE THREAD

**Issue by Vagh-s** [xuejianxianzun/PixivBatchDownloader#366]
**What functionality do you want?**
add duplicate download redundancy checker for user cover and user avatar

**What is the purpose to solve?**
to resolve redundant downloads 

**Does other software have such functions for reference?**

**Additional context**

**Comment by xuejianxianzun** [comment]
I don't plan to do this feature because saving user avatars is not a high-frequency operation. Many users don't use this feature.
Moreover, the downloader does not have permission to check the files on the hard disk, so it cannot truly prevent repeated downloads.
Duplicate downloaded avatars have parentheses  `(` `)` in their file names so they can be easily found and deleted.
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/3ee80e76-4c65-438b-8678-d16f9f68b68a)

**Comment by Vagh-s** [comment]
can you not implement the similar include it to download record?
