### ISSUE TITLE
Is it possible to automatically name individually downloaded files?

### ISSUE THREAD

**Issue by Triramama** [xuejianxianzun/PixivBatchDownloader#376]
I don't think the extension does this, it names images according to "naming rule" only with batch download, when I get just one picture the filename is gibberish

**Comment by xuejianxianzun** [comment]
Check this reason：

The problem with abnormal file names

Certain extensions take over the browser's downloads, so the downloads I set up will be handled by them, possibly losing the filenames I set.

There are a lot of these extensions (even if they are not running on Pixiv and Fanbox will cause this problem). In recent feedback, the extension causing this issue is usually Patreon Downloader.

If the downloaded file name is unusual, please disable such extensions while downloading.
