### ISSUE TITLE
Ability to synchronize bookmarked works across multiple accounts

### ISSUE THREAD

**Issue by GCUSCOCOa** [xuejianxianzun/PixivBatchDownloader#392]
**What functionality do you want?**
1) The ability to export the list of bookmarked works.
2) The ability to follow all bookmarked works at once.

**What is the purpose to solve?**
I have multiple accounts and would like to be able to synchronize my bookmarked works list.

**Comment by cyfxzh** [comment]
Try [https://github.com/Ziqing19/LabelPixivBookmarks](url)

**Comment by GCUSCOCOa** [comment]
I have tried this script but it is stuck in the middle, please advise if you don't mind.
I output the file with "Backup Bookmarks" in Other Functrin, then loaded the file with "Import Bookmarks" in an account with no bookmarks, but nothing changed.

**Comment by xuejianxianzun** [comment]
This feature is useful, but I don't know what percentage of users it will be useful for. Because most users should only have one account. I haven't decided whether to add this feature yet.

Currently, you can do this through the "Bookmark works after downloading" function. But this requires grabbing the piece first, so it takes double the time.

1. Enable Bookmark works after downloading.
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/df691f58-509b-41bc-9122-0fdefe40d14e)

2. You can set the downloaded image size to small, because downloading is not our purpose.
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/36d6cdc6-9046-4a2e-a204-f52f0e060dd5)

3. Use another account to open your bookmark page, capture and download all your bookmarks.

When your crawl is complete, you can export the crawl results. Later, when you log in to other accounts, you can import the crawl results to avoid repeated crawling.

**Comment by cyfxzh** [comment]
> I have tried this script but it is stuck in the middle, please advise if you don't mind. I output the file with "Backup Bookmarks" in Other Functrin, then loaded the file with "Import Bookmarks" in an account with no bookmarks, but nothing changed.

Today i tried this function, it still work, there are still a few steps after you choose the file you want to import, maybe you forget. i recommend this script because it's really faster than this batch downloader

**Comment by GCUSCOCOa** [comment]
> This feature is useful, but I don't know what percentage of users it will be useful for. Because most users should only have one account. I haven't decided whether to add this feature yet.

I understand. Your work is excellent even without this feature. Thank you very much.

**Comment by GCUSCOCOa** [comment]
> Today i tried this function, it still work, there are still a few steps after you choose the file you want to import, maybe you forget. i recommend this script because it's really faster than this batch downloader

I tried again and this time it worked. Thanks for the advice.

**Comment by xuejianxianzun** [comment]
This feature has been added in version 16.8.0.

**Comment by GCUSCOCOa** [comment]
> This feature has been added in version 16.8.0.

Thank you so much. Your response is really great!
