### ISSUE TITLE
I would like the ability to download files and folders after they have been zipped.

### ISSUE THREAD

**Issue by dog6o** [xuejianxianzun/PixivBatchDownloader#445]
**What functionality do you want?**
I would like the ability to download files and folders after they have been zipped.

**What is the purpose to solve?**
none

**Does other software have such functions for reference?**
It exists as a paid feature in the Pixiv Toolkit, which is eager to make money.

**Additional context**
none

**Comment by xuejianxianzun** [comment]
I have no plans to do this at the moment. This is mainly because this downloader is designed for large batch downloads.
When downloading large quantities, the zip package may need to be divided into multiple compressed packages. And the size of a single zip package created in the browser cannot be too large (perhaps 500 MB).
In addition, the downloader can resume unfinished downloads. Suppose the user first downloads 100 images, then closes the tab, and reopens it, the downloader can continue downloading. But when packaging, what about the first 100 files? To solve this problem, the downloaded files need to be written to temporary storage, which will bring additional overhead.
Of course, part of the reason is that I am lazy. In fact, there are not many users who have this demand, so I don’t have enough motivation to make it.

**Comment by dog6o** [comment]
Copy that.
