### ISSUE TITLE
Unable to do batch download

### ISSUE THREAD

**Issue by DestinoAzell** [xuejianxianzun/PixivBatchDownloader#49]
since 2 days ago I'm
Unable to do batch download even by one illustration let alone trying to download the whole album.
I hope this can be fix.
Thanks admin-san!

**Comment by xuejianxianzun** [comment]
I think this may be an unrepresentative case.

There is a button "Reset Settings" at the bottom of the download panel, please reset the settings and try again.

Alternatively, check if the downloader is the latest version 3.9.2.

If the issue is not resolved, please report some details, such as:
operating system
Browser version
Page URL
Screenshots

good luck!

**Comment by DestinoAzell** [comment]
I am using this script https://greasyfork.org/zh-CN/scripts/24252-%E4%BB%99%E5%B0%8A-pixiv-%E5%9B%BE%E7%89%87%E6%89%B9%E9%87%8F%E4%B8%8B%E8%BD%BD%E5%99%A8-%E8%AF%B7%E5%88%87%E6%8D%A2%E5%88%B0-chrome-%E6%89%A9%E5%B1%95%E7%89%88
I guess it doesn't work anymore.

At this point I'll just use thev 3.9.2
Thanks for the feedback
