### ISSUE TITLE
Only downloads .txt files 

### ISSUE THREAD

**Issue by ripter12** [xuejianxianzun/PixivBatchDownloader#55]
Hi, 

since a couple of days this extension doesn't work for me anymore. It does download videos and converts them into webms, but it doesn't download any pictures, I only get .txt files telling me the download failed. (At the download screen it shows the correct file size for videos, but 0 KB for any picture I try to download.)
I already reset the settings, deleted the extension and added the newest version, but nothing seems to work. Even changing my IP does nothing. 

Is this a problem for anyone else or is it something on my end? 
Thanks for your help and thanks for your extension, because when it worked for me,  it did perfectly.

**Comment by xuejianxianzun** [comment]
This is because pixiv's image url has a new domain name and I have adapted it.
If you installed the extension from the Chrome web store, please wait to update to 4.0.4 (currently under review, not sure when it will be released).
Before the review is complete, you can also download the offline installation package on the releases page:
https://github.com/xuejianxianzun/PixivBatchDownloader/releases

**Comment by ripter12** [comment]
my man
