### ISSUE TITLE
{tags_translate} causing OS Path issues and renaming conflicts

### ISSUE THREAD

**Issue by ndaley7** [xuejianxianzun/PixivBatchDownloader#84]
Hopefully this will translate to Chinese, but if that is not the case, please let me know.

Would it be possible to modify this tag so it only had the translated tags for the work?

Some of the characters  between the (Japanese Characters and Sometimes Emojis) cause issues with the path structure and naming of the images, making the 'Save As' dialog come up repeatedly due to induced naming conflicts.

If not modify the tag, could an additional one be added: {tags_translate_only} so that it appends only the translated tags if available?

An alternate solution, would be to offer an  option to write all tags to a text file in each folder called "tags.csv" or "tags.txt".

please let me know if I can provide more details!

**Comment by xuejianxianzun** [comment]
Can you provide an example that causes problems?
Regarding {tags_translate_only}, I will initiate an investigation and then decide whether to add it.
The alternative method you proposed is not feasible because it is not convenient for users to search for files. Saving the tag in the file name is very helpful for searching files.

**Comment by xuejianxianzun** [comment]
Need more information

**Comment by CELICA3** [comment]
is it possible to strip the length of naming string to within Windows accepted limit and omit any special characters?
#98
